### ISSUE TITLE
STDERR: E: There are problems and -y was used without --force-yes

### ISSUE THREAD

**Issue by joelhandwell** [haapp/w_percona#34]
```kitchen converge``` started to have following error:

```
   Recipe: percona::cluster
         * apt_package[percona-xtradb-cluster-56] action install

           ================================================================================
           Error executing action `install` on resource 'apt_package[percona-xtradb-cluster-56]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '100'
           ---- Begin output of apt-get -q -y install percona-xtradb-cluster-56=5.6.32-25.17-1.trusty ----
           STDOUT: Reading package lists...
           Building dependency tree...
           Reading state information...
           The following extra packages will be installed:
             iproute libaio1 libdbd-mysql-perl libdbi-perl libev4 libmysqlclient18
             mysql-common percona-xtrabackup percona-xtradb-cluster-client-5.6
             percona-xtradb-cluster-common-5.6 percona-xtradb-cluster-galera-3
             percona-xtradb-cluster-galera-3.x percona-xtradb-cluster-server-5.6 socat
           Suggested packages:
             libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl
             libsql-statement-perl tinyca pv qpress
           The following NEW packages will be installed:
             iproute libaio1 libdbd-mysql-perl libdbi-perl libev4 libmysqlclient18
             mysql-common percona-xtrabackup percona-xtradb-cluster-56
             percona-xtradb-cluster-client-5.6 percona-xtradb-cluster-common-5.6
             percona-xtradb-cluster-galera-3 percona-xtradb-cluster-galera-3.x
             percona-xtradb-cluster-server-5.6 socat
           0 upgraded, 15 newly installed, 0 to remove and 94 not upgraded.
           Need to get 14.2 MB of archives.
           After this operation, 139 MB of additional disk space will be used.
           WARNING: The following packages cannot be authenticated!
             percona-xtradb-cluster-common-5.6 percona-xtradb-cluster-client-5.6
             percona-xtradb-cluster-galera-3.x percona-xtrabackup
             percona-xtradb-cluster-server-5.6 percona-xtradb-cluster-galera-3
             percona-xtradb-cluster-56
           STDERR: E: There are problems and -y was used without --force-yes
           ---- End output of apt-get -q -y install percona-xtradb-cluster-56=5.6.32-25.17-1.trusty ----
           Ran apt-get -q -y install percona-xtradb-cluster-56=5.6.32-25.17-1.trusty returned 100

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/percona/recipes/cluster.rb

            27:   package node["percona"]["cluster"]["package"] do
            28:     # The package starts up immediately, then additional config is added and the
            29:     # restart command fails to work. Instead, stop the database before changing
            30:     # the configuration.
            31:     notifies :stop, "service[mysql]", :immediately
            32:   end
            33: when "rhel"

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/percona/recipes/cluster.rb:27:in `from_file'

           apt_package("percona-xtradb-cluster-56") do
             package_name "percona-xtradb-cluster-56"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "percona"
             recipe_name "cluster"
           end

           Platform:
           ---------
           x86_64-linux
```

**Comment by misoman** [comment]
we have to add to percona cookbook attribute:
default['percona']['apt']['key'] = '8507EFA5'

base on this article: https://www.percona.com/blog/2016/10/13/new-signing-key-for-percona-debian-and-ubuntu-packages/

**Comment by joelhandwell** [comment]
Ok can you create Pull Request with tests for the fix?

**Comment by joelhandwell** [comment]
Fixed by https://github.com/haapp/w_percona/pull/35
